-- ==========================================================================
--  17 — CARTE COMPLÈTE DE MELYZA TACOS
--  --------------------------------------------------------------------------
--  144 plats, 107 formats, 613 suppléments, relevés sur les
--  affiches officielles du restaurant.
--
--  Le script trouve le restaurant par son nom (contenant « melyza ») : il doit
--  donc exister avant de lancer ce fichier. Rien n'est écrasé — un plat déjà
--  présent sous le même nom est laissé tel quel, ce qui rend le script
--  rejouable et permet au restaurateur de retoucher sa carte sans crainte.
--
--  Les photos ne sont pas incluses : le restaurateur les ajoute lui-même
--  depuis son espace, plat par plat.
-- ==========================================================================

-- Vérification préalable : le restaurant existe-t-il ?
do $$
begin
  if not exists (select 1 from public.restaurants where name ilike '%melyza%') then
    raise exception 'Aucun restaurant dont le nom contient « melyza ». Créez sa fiche d''abord.';
  end if;
end $$;


-- ------------------------------------------------------------- LES PLATS
with resto as (select id from public.restaurants where name ilike '%melyza%' order by created_at limit 1),
plats (cat, nom, descr, prix, ordre) as (values
  ('pizza', 'Pizza Végétarienne', 'Sauce tomate, mozzarella, cheddar, champignons, tomates fraîches, poivrons, herbes de Provence. Suppléments facturés ×2 en format Méga.', 600, 0),
  ('pizza', 'Pizza Thon', 'Sauce tomate, mozzarella, cheddar, thon, poivron, herbes de Provence. Suppléments facturés ×2 en format Méga.', 700, 1),
  ('pizza', 'Pizza Chicken', 'Sauce tomate, mozzarella, cheddar, poulet, poivrons, herbes de Provence. Suppléments facturés ×2 en format Méga.', 750, 2),
  ('pizza', 'Pizza Américaine', 'Sauce tomate, mozzarella, cheddar, viande hachée, poivrons, herbes de Provence. Suppléments facturés ×2 en format Méga.', 800, 3),
  ('pizza', 'Pizza Tropicale', 'Sauce tomate, mozzarella, cheddar, poulet, champignons, poivrons, herbes de Provence. Suppléments facturés ×2 en format Méga.', 900, 4),
  ('pizza', 'Pizza Orientale', 'Sauce tomate, mozzarella, cheddar, merguez, œuf, poivrons, herbes de Provence. Suppléments facturés ×2 en format Méga.', 900, 5),
  ('pizza', 'Pizza Barbecue', 'Sauce tomate, mozzarella, cheddar, viande hachée épicée, oignons, poivrons, herbes de Provence. Suppléments facturés ×2 en format Méga.', 900, 6),
  ('pizza', 'Pizza Spéciale', 'Sauce tomate, mozzarella, cheddar, viande hachée, poulet, merguez, poivrons, herbes de Provence. Suppléments facturés ×2 en format Méga.', 1100, 7),
  ('pizza', 'Pizza Mix Spécial', 'Sauce tomate, mozzarella, cheddar, viande hachée, poulet, champignons, poivrons, herbes de Provence. Suppléments facturés ×2 en format Méga.', 1100, 8),
  ('pizza', 'Pizza Fish House', 'Sauce tomate, mozzarella, cheddar, thon, crevettes, calamar, poivrons, herbes de Provence. Suppléments facturés ×2 en format Méga.', 1250, 9),
  ('pizza', 'Pizza Classique', 'Sauce tomate, mozzarella, cheddar, crevettes, champignons, poivrons, herbes de Provence. Suppléments facturés ×2 en format Méga.', 1250, 10),
  ('pizza', 'Pizza Queen', 'Sauce tomate, mozzarella, cheddar, poulet, ananas. Suppléments facturés ×2 en format Méga.', 900, 11),
  ('pizza', 'Pizza 3 Fromages', 'Sauce blanche, mozzarella, cheddar, camembert, herbes de Provence. Suppléments facturés ×2 en format Méga.', 800, 12),
  ('pizza', 'Pizza 4 Fromages', 'Sauce blanche, mozzarella, cheddar, gruyère, roquefort, herbes de Provence. Suppléments facturés ×2 en format Méga.', 1150, 13),
  ('pizza', 'Pizza Parisienne', 'Sauce blanche, mozzarella, cheddar, poulet, herbes de Provence. Suppléments facturés ×2 en format Méga.', 850, 14),
  ('pizza', 'Pizza Poulet Fumé', 'Sauce blanche, mozzarella, cheddar, poulet fumé, herbes de Provence. Suppléments facturés ×2 en format Méga.', 850, 15),
  ('pizza', 'Pizza Chicago', 'Sauce blanche, mozzarella, cheddar, viande hachée, saucisson fumé, herbes de Provence. Suppléments facturés ×2 en format Méga.', 950, 16),
  ('pizza', 'Pizza Chèvre Miel', 'Sauce blanche, gruyère, chèvre, miel, noix. Suppléments facturés ×2 en format Méga.', 900, 17),
  ('pizza', 'Pizza Saumon', 'Sauce blanche, mozzarella, cheddar, saumon, herbes de Provence. Suppléments facturés ×2 en format Méga.', 1300, 18),
  ('pizza', 'Pizza Spicy', 'Sauce tomate, cheddar, mozzarella, poulet épicé, huile piquante, poivron, herbes de Provence. Suppléments facturés ×2 en format Méga.', 900, 19),
  ('pizza', 'Pizza Anchois', 'Sauce tomate, cheddar, mozzarella, câpres, anchois, huile d’olive, herbes de Provence. Suppléments facturés ×2 en format Méga.', 950, 20),
  ('pizza', 'Pizza Boursin', 'Sauce blanche, boursin, mozzarella, cheddar, poulet fumé, herbes de Provence. Suppléments facturés ×2 en format Méga.', 950, 21),
  ('pizza', 'Pizza Pepperonis', 'Sauce tomate, mozzarella, cheddar, pepperonis. Suppléments facturés ×2 en format Méga.', 1100, 22),
  ('pizza', 'Pizza Végé Suprême', 'Sauce tomate, cheddar, mozzarella, tomate fraîche, champignons, maïs, oignon, poivron, herbes de Provence. Suppléments facturés ×2 en format Méga.', 700, 23),
  ('pizza', 'Pizza Raclette', 'Sauce tomate, cheddar, mozzarella, raclette artisanale, herbes de Provence. Suppléments facturés ×2 en format Méga.', 900, 24),
  ('pizza', 'Pizza Spéciale Melyza', 'La signature de la maison, garniture généreuse. Suppléments facturés ×2 en format Méga.', 1500, 25),
  ('pizza', 'My Pizza', 'Six (6) ingrédients au choix, composez la vôtre. Suppléments facturés ×2 en format Méga.', 1600, 26),
  ('pizza', 'Pizza Quatre Saisons', 'Poulet, viande hachée, merguez, champignons. Uniquement en format Méga. Suppléments facturés ×2 en format Méga.', 2600, 27),
  ('tacos', 'Le Suisse', 'Escalope de poulet, fromage fondu, jambon de dinde, oignons caramélisés, gratiné cheddar, poivron, sauce au choix.', 750, 28),
  ('tacos', 'Gratiné Chèvre Miel', 'Au poulet, gratiné chèvre et miel.', 700, 29),
  ('tacos', 'Gratiné Boursin', 'Poulet, cheddar, boursin, sauce algérienne.', 750, 30),
  ('tacos', 'Le Frenchy', 'Viande hachée, camembert, salami, oignons caramélisés, sauce miel moutarde.', 800, 31),
  ('tacos', 'Le Fumé', 'Cordon bleu, sauce barbecue, gratiné cheddar.', 700, 32),
  ('tacos', 'Tacos Tenders', 'Tenders croustillants, frites et sauce au choix.', 600, 33),
  ('tacos', 'Le Mythique', 'Gratiné gouda, cordon bleu, sauce barbecue.', 750, 34),
  ('tacos', 'Le Légendaire', 'Gratiné mozzarella, nuggets, sauce burger.', 750, 35),
  ('tacos', 'Le Montagnard', 'Gratinée raclette, jambon de poulet, tenders, sauce au choix.', 750, 36),
  ('tacos', 'Le Fameux', 'Gratiné cheddar, viande hachée, champignons, sauce algérienne.', 850, 37),
  ('burger', 'Big Melyza', '2 steaks, gruyère, champignons, cornichons, poivrons, sauce à l’ail.', 950, 38),
  ('burger', 'Big Crispy', 'Poulet pané, salade, tomate, oignons.', 650, 39),
  ('burger', 'Franche Burger', '2 steaks, camembert, cheddar, cornichons, sauce big burger.', 900, 40),
  ('burger', 'Mozzarella Burger', '2 steaks, jambon de dinde, mozzarella, oignons caramélisés, champignons.', 850, 41),
  ('burger', 'Big Fast', '2 steaks, cheddar, œuf, oignons caramélisés.', 750, 42),
  ('burger', 'Le Poivre', 'Steak haché, poulet haché, gouda, oignons caramélisés, sauce au poivre.', 750, 43),
  ('sandwich', 'Melyza Spécial', 'Steak haché, fromage blanc, cheddar, salade, tomate, cornichons, champignons, oignons caramélisés, omelette, frites.', 900, 44),
  ('sandwich', 'Sandwich Avocat', 'Avocat, thon, tomate, salade, fromage à tartiner.', 700, 45),
  ('sandwich', 'Sandwich Poulet', 'Poulet, camembert, cheddar, salade, tomate, cornichons, oignons caramélisés, frites.', 700, 46),
  ('autre', 'Chicken Box', 'Tenders, nuggets et cordon bleu réunis dans un seau.', 600, 47),
  ('autre', 'Tenders', 'Poulet croustillant, sauce au choix.', 350, 48),
  ('autre', 'Nuggets', 'Nuggets de poulet, sauce au choix.', 300, 49),
  ('autre', 'Cordon Bleu', 'Cordon bleu pané, sauce au choix.', 450, 50),
  ('autre', 'Tacos Bowl', 'Escalopes de poulet, cordon bleu, nuggets, tenders, sauces au choix.', 700, 51),
  ('autre', 'Bowl Chèvre Miel Poulet', 'Frites, poulet, sauce fromage, cheddar gratiné, chèvre, miel.', 850, 52),
  ('autre', 'Spicy Bowl', 'Tenders, piment, sauce samouraï.', 800, 53),
  ('autre', 'Salade César', 'Salade, poulet, croûtons, parmesan.', 650, 54),
  ('autre', 'Salade de Thon', 'Thon, crudités et œuf.', 450, 55),
  ('autre', 'Salade Saumon Avocat', 'Saumon, avocat et crevettes.', 1050, 56),
  ('autre', 'Salade Melyza', 'La grande salade composée de la maison.', 950, 57),
  ('autre', 'Assiette de Fromages', 'Plateau de fromages affinés.', 1100, 58),
  ('dessert', 'Cheesecake Fraise', 'Cheesecake maison, coulis de fraise.', 400, 59),
  ('dessert', 'Cheesecake Lotus', 'Cheesecake maison, spéculoos Lotus.', 500, 60),
  ('dessert', 'Cheesecake Oreo', 'Cheesecake maison, biscuits Oreo.', 500, 61),
  ('dessert', 'Cheesecake Bueno', 'Cheesecake maison, Kinder Bueno.', 500, 62),
  ('dessert', 'Cheesecake Citron', 'Cheesecake maison, citron.', 500, 63),
  ('dessert', 'Cheesecake Nutella', 'Cheesecake maison, Nutella.', 600, 64),
  ('dessert', 'Cheesecake Pistache', 'Cheesecake maison, pistache.', 700, 65),
  ('dessert', 'Crêpe Nutella', 'Crêpe gourmande au Nutella.', 400, 66),
  ('dessert', 'Crêpe Banane', 'Crêpe gourmande à la banane.', 550, 67),
  ('dessert', 'Crêpe Pistache', 'Crêpe gourmande à la pistache.', 550, 68),
  ('dessert', 'Crêpe Lotus', 'Crêpe gourmande au Lotus.', 600, 69),
  ('dessert', 'Crêpe Fraise', 'Crêpe gourmande à la fraise.', 650, 70),
  ('dessert', 'Crêpe Oreo', 'Crêpe gourmande aux Oreo.', 650, 71),
  ('dessert', 'Crêpe Fruits Secs', 'Crêpe gourmande aux fruits secs.', 650, 72),
  ('dessert', 'Crêpe Fruits', 'Crêpe gourmande aux fruits frais.', 700, 73),
  ('dessert', 'Crêpe Bounty', 'Crêpe gourmande au Bounty.', 700, 74),
  ('dessert', 'Crêpe Bueno', 'Crêpe gourmande au Kinder Bueno.', 800, 75),
  ('dessert', 'Crêpe El Mordjene', 'Crêpe gourmande à la pâte El Mordjene.', 350, 76),
  ('dessert', 'Crêpe Spéciale', 'La grande crêpe garnie de la maison.', 1000, 77),
  ('dessert', 'Mousse au Chocolat', 'Mousse maison au chocolat noir.', 300, 78),
  ('dessert', 'Crème Brûlée', 'Crème vanille, caramel craquant.', 350, 79),
  ('dessert', 'Fondant au Chocolat', 'Cœur coulant, servi tiède.', 450, 80),
  ('dessert', 'Maxi Fruits', 'Grande coupe de fruits frais.', 900, 81),
  ('dessert', 'Tiramisu', 'Tiramisu classique au café.', 350, 82),
  ('dessert', 'Tiramisu Pistache', 'Tiramisu à la pistache.', 400, 83),
  ('dessert', 'Tiramisu Chocolat', 'Tiramisu au chocolat.', 350, 84),
  ('dessert', 'Tiramisu Citron', 'Tiramisu au citron.', 350, 85),
  ('boisson', 'Espresso', 'Café serré.', 150, 86),
  ('boisson', 'Doppio', 'Double espresso.', 250, 87),
  ('boisson', 'Espresso Kinder', 'Espresso façon Kinder.', 300, 88),
  ('boisson', 'Americano', 'Café allongé, glacé ou nature.', 250, 89),
  ('boisson', 'Affogato', 'Espresso versé sur une glace vanille.', 300, 90),
  ('boisson', 'Thé Infusion', 'Infusion au choix.', 150, 91),
  ('boisson', 'Cappuccino', 'Café, lait, mousse onctueuse.', 350, 92),
  ('boisson', 'Mocha', 'Café, chocolat et lait.', 350, 93),
  ('boisson', 'Flat White', 'Café, lait micro-moussé.', 350, 94),
  ('boisson', 'Latte', 'Café allongé au lait.', 350, 95),
  ('boisson', 'Dalgona Coffee', 'Café fouetté, glacé ou nature.', 350, 96),
  ('boisson', 'Ice Tea', 'Thé glacé maison.', 250, 97),
  ('boisson', 'Boule de Glace', 'Une boule au parfum de votre choix.', 120, 98),
  ('boisson', 'Boule de Fraise', 'Une boule à la fraise.', 140, 99),
  ('boisson', 'Banana Split', 'Banane, glace, chantilly et chocolat.', 200, 100),
  ('boisson', 'Milkshake Vanille', 'Milkshake onctueux à la vanille.', 350, 101),
  ('boisson', 'Milkshake Caramel Beurre Salé', 'Milkshake au caramel beurre salé.', 450, 102),
  ('boisson', 'Milkshake Nutella', 'Milkshake au Nutella.', 450, 103),
  ('boisson', 'Milkshake Nutella Banane', 'Milkshake Nutella et banane.', 550, 104),
  ('boisson', 'Milkshake Snickers', 'Milkshake au Snickers.', 450, 105),
  ('boisson', 'Milkshake Bueno', 'Milkshake au Kinder Bueno.', 450, 106),
  ('boisson', 'Milkshake KitKat', 'Milkshake au KitKat.', 450, 107),
  ('boisson', 'Milkshake Oreo', 'Milkshake aux Oreo.', 550, 108),
  ('boisson', 'Milkshake Avocat', 'Milkshake à l’avocat.', 800, 109),
  ('boisson', 'Mojito Classique', 'Citron vert, menthe fraîche.', 450, 110),
  ('boisson', 'Pink Mojito', 'Mojito version fruits rouges.', 500, 111),
  ('boisson', 'Blue Mojito', 'Mojito au blue curaçao.', 500, 112),
  ('boisson', 'Mojito Fraise Menthe', 'Fraise et menthe fraîche.', 600, 113),
  ('boisson', 'Mojito Kiwi', 'Mojito au kiwi.', 700, 114),
  ('boisson', 'Mojito Inspiration du Chef', 'La création mojito du moment.', 800, 115),
  ('boisson', 'Jus de Citron', 'Pressé minute.', 400, 116),
  ('boisson', 'Jus d’Orange', 'Pressé minute.', 350, 117),
  ('boisson', 'Jus de Banane', 'Fruit frais mixé.', 350, 118),
  ('boisson', 'Jus de Fraise', 'Fruit frais mixé.', 400, 119),
  ('boisson', 'Jus de Pêche', 'Fruit frais mixé.', 350, 120),
  ('boisson', 'Jus de Grenade', 'Pressé minute.', 400, 121),
  ('boisson', 'Cocktail de Fruits', 'Assortiment de fruits frais.', 500, 122),
  ('boisson', 'Cocktail Florida', 'Orange, ananas, fraise, citron.', 450, 123),
  ('boisson', 'Cocktail Rio', 'Citron, menthe, limonade, blue curaçao.', 450, 124),
  ('boisson', 'Cocktail Fleur d’Amour', 'Mangue, fraise, lait de coco.', 600, 125),
  ('boisson', 'Cocktail The Pink Lady', 'Ananas, goyave, fraise, citron.', 650, 126),
  ('boisson', 'Cocktail Hawaï', 'Ananas, orange, lait de coco.', 650, 127),
  ('boisson', 'Cocktail Bahama-Mama', 'Ananas, orange, fraise, grenadine.', 650, 128),
  ('boisson', 'Cocktail Bora-Bora', 'Citron, fruit de la passion, Sprite.', 650, 129),
  ('boisson', 'Cocktail Blue Lagoon', 'Limonade, citron, blue curaçao.', 650, 130),
  ('boisson', 'Cocktail Pina Colada', 'Ananas, lait de coco.', 700, 131),
  ('boisson', 'Cocktail Bahamas Kiwi', 'Kiwi et agrumes.', 750, 132),
  ('boisson', 'Cocktail Blue Star', 'Limonade, fruits rouges, blue curaçao.', 750, 133),
  ('boisson', 'Cocktail Strawberry Colada', 'Fraise, ananas.', 800, 134),
  ('boisson', 'Cocktail Inspiration du Chef', 'La création du moment.', 800, 135),
  ('boisson', 'Smoothie Pomme Kiwi', 'Pomme et kiwi mixés.', 700, 136),
  ('boisson', 'Smoothie Mangue Passion', 'Mangue et fruit de la passion.', 650, 137),
  ('boisson', 'Morning Smoothie', 'Le smoothie vitaminé du matin.', 750, 138),
  ('boisson', 'Frappé Noix', 'Frappé onctueux aux noix.', 700, 139),
  ('boisson', 'Frappuccino Vanille', 'Café glacé fouetté, vanille.', 350, 140),
  ('boisson', 'Frappuccino Caramel', 'Café glacé fouetté, caramel.', 350, 141),
  ('boisson', 'Frappuccino Fraise', 'Frappé glacé à la fraise.', 400, 142),
  ('boisson', 'Frappuccino Banane', 'Frappé glacé à la banane.', 400, 143)
)
insert into public.menu_items (restaurant_id, category_id, name, description, price, sort_order, is_available)
select r.id, c.id, p.nom, p.descr, p.prix, p.ordre, true
  from plats p
  cross join resto r
  join public.categories c on c.slug = p.cat
 where not exists (
   select 1 from public.menu_items m where m.restaurant_id = r.id and m.name = p.nom
 );


-- ---------------------------------------------------------- LES FORMATS
-- Solo/Menu, Small/Méga : le client en choisit UN, et c'est lui qui fixe le prix.
with resto as (select id from public.restaurants where name ilike '%melyza%' order by created_at limit 1),
formats (plat, nom, prix, ordre) as (values
  ('Pizza Végétarienne', 'Small', 600, 0),
  ('Pizza Végétarienne', 'Méga', 1700, 1),
  ('Pizza Thon', 'Small', 700, 0),
  ('Pizza Thon', 'Méga', 1650, 1),
  ('Pizza Chicken', 'Small', 750, 0),
  ('Pizza Chicken', 'Méga', 1950, 1),
  ('Pizza Américaine', 'Small', 800, 0),
  ('Pizza Américaine', 'Méga', 2050, 1),
  ('Pizza Tropicale', 'Small', 900, 0),
  ('Pizza Tropicale', 'Méga', 2200, 1),
  ('Pizza Orientale', 'Small', 900, 0),
  ('Pizza Orientale', 'Méga', 1950, 1),
  ('Pizza Barbecue', 'Small', 900, 0),
  ('Pizza Barbecue', 'Méga', 2100, 1),
  ('Pizza Spéciale', 'Small', 1100, 0),
  ('Pizza Spéciale', 'Méga', 2250, 1),
  ('Pizza Mix Spécial', 'Small', 1100, 0),
  ('Pizza Mix Spécial', 'Méga', 2250, 1),
  ('Pizza Fish House', 'Small', 1250, 0),
  ('Pizza Fish House', 'Méga', 2650, 1),
  ('Pizza Classique', 'Small', 1250, 0),
  ('Pizza Classique', 'Méga', 2500, 1),
  ('Pizza Queen', 'Small', 900, 0),
  ('Pizza Queen', 'Méga', 1650, 1),
  ('Pizza 3 Fromages', 'Small', 800, 0),
  ('Pizza 3 Fromages', 'Méga', 1900, 1),
  ('Pizza 4 Fromages', 'Small', 1150, 0),
  ('Pizza 4 Fromages', 'Méga', 2250, 1),
  ('Pizza Parisienne', 'Small', 850, 0),
  ('Pizza Parisienne', 'Méga', 1950, 1),
  ('Pizza Poulet Fumé', 'Small', 850, 0),
  ('Pizza Poulet Fumé', 'Méga', 1950, 1),
  ('Pizza Chicago', 'Small', 950, 0),
  ('Pizza Chicago', 'Méga', 2250, 1),
  ('Pizza Chèvre Miel', 'Small', 900, 0),
  ('Pizza Chèvre Miel', 'Méga', 2200, 1),
  ('Pizza Saumon', 'Small', 1300, 0),
  ('Pizza Saumon', 'Méga', 2500, 1),
  ('Pizza Spicy', 'Small', 900, 0),
  ('Pizza Spicy', 'Méga', 2150, 1),
  ('Pizza Anchois', 'Small', 950, 0),
  ('Pizza Anchois', 'Méga', 2250, 1),
  ('Pizza Boursin', 'Small', 950, 0),
  ('Pizza Boursin', 'Méga', 2200, 1),
  ('Pizza Pepperonis', 'Small', 1100, 0),
  ('Pizza Pepperonis', 'Méga', 2250, 1),
  ('Pizza Végé Suprême', 'Small', 700, 0),
  ('Pizza Végé Suprême', 'Méga', 1800, 1),
  ('Pizza Raclette', 'Small', 900, 0),
  ('Pizza Raclette', 'Méga', 2200, 1),
  ('Pizza Spéciale Melyza', 'Small', 1500, 0),
  ('Pizza Spéciale Melyza', 'Méga', 3200, 1),
  ('My Pizza', 'Small', 1600, 0),
  ('My Pizza', 'Méga', 2800, 1),
  ('Le Suisse', 'Solo', 750, 0),
  ('Le Suisse', 'Menu (frites + boisson)', 950, 1),
  ('Gratiné Chèvre Miel', 'Solo', 700, 0),
  ('Gratiné Chèvre Miel', 'Menu (frites + boisson)', 900, 1),
  ('Gratiné Boursin', 'Solo', 750, 0),
  ('Gratiné Boursin', 'Menu (frites + boisson)', 950, 1),
  ('Le Frenchy', 'Solo', 800, 0),
  ('Le Frenchy', 'Menu (frites + boisson)', 1000, 1),
  ('Le Fumé', 'Solo', 700, 0),
  ('Le Fumé', 'Menu (frites + boisson)', 900, 1),
  ('Tacos Tenders', 'Solo', 600, 0),
  ('Tacos Tenders', 'Menu (frites + boisson)', 800, 1),
  ('Le Mythique', 'Solo', 750, 0),
  ('Le Mythique', 'Menu (frites + boisson)', 950, 1),
  ('Le Légendaire', 'Solo', 750, 0),
  ('Le Légendaire', 'Menu (frites + boisson)', 950, 1),
  ('Le Montagnard', 'Solo', 750, 0),
  ('Le Montagnard', 'Menu (frites + boisson)', 950, 1),
  ('Le Fameux', 'Solo', 850, 0),
  ('Le Fameux', 'Menu (frites + boisson)', 1050, 1),
  ('Big Melyza', 'Solo', 950, 0),
  ('Big Melyza', 'Menu (frites + boisson)', 1150, 1),
  ('Big Crispy', 'Solo', 650, 0),
  ('Big Crispy', 'Menu (frites + boisson)', 850, 1),
  ('Franche Burger', 'Solo', 900, 0),
  ('Franche Burger', 'Menu (frites + boisson)', 1100, 1),
  ('Mozzarella Burger', 'Solo', 850, 0),
  ('Mozzarella Burger', 'Menu (frites + boisson)', 1050, 1),
  ('Big Fast', 'Solo', 750, 0),
  ('Big Fast', 'Menu (frites + boisson)', 950, 1),
  ('Le Poivre', 'Solo', 750, 0),
  ('Le Poivre', 'Menu (frites + boisson)', 950, 1),
  ('Melyza Spécial', 'Solo', 900, 0),
  ('Melyza Spécial', 'Menu (frites + boisson)', 1100, 1),
  ('Sandwich Avocat', 'Solo', 700, 0),
  ('Sandwich Avocat', 'Menu (frites + boisson)', 900, 1),
  ('Sandwich Poulet', 'Solo', 700, 0),
  ('Sandwich Poulet', 'Menu (frites + boisson)', 900, 1),
  ('Tenders', 'M — 3 pièces', 350, 0),
  ('Tenders', 'L — 6 pièces', 550, 1),
  ('Tenders', 'XL — 12 pièces', 1100, 2),
  ('Nuggets', 'M — 3 pièces', 300, 0),
  ('Nuggets', 'L — 6 pièces', 400, 1),
  ('Nuggets', 'XL — 12 pièces', 650, 2),
  ('Cordon Bleu', 'M — 3 pièces', 450, 0),
  ('Cordon Bleu', 'L — 6 pièces', 850, 1),
  ('Cordon Bleu', 'XL — 12 pièces', 1550, 2),
  ('Tacos Bowl', 'Solo', 700, 0),
  ('Tacos Bowl', 'Menu (frites + boisson)', 900, 1),
  ('Bowl Chèvre Miel Poulet', 'Solo', 850, 0),
  ('Bowl Chèvre Miel Poulet', 'Menu (frites + boisson)', 1050, 1),
  ('Spicy Bowl', 'Solo', 800, 0),
  ('Spicy Bowl', 'Menu (frites + boisson)', 1000, 1)
)
insert into public.menu_variants (menu_item_id, name, price, sort_order, is_active)
select m.id, f.nom, f.prix, f.ordre, true
  from formats f
  cross join resto r
  join public.menu_items m on m.restaurant_id = r.id and m.name = f.plat
 where not exists (
   select 1 from public.menu_variants v where v.menu_item_id = m.id and v.name = f.nom
 );


-- ------------------------------------------------------ LES SUPPLÉMENTS
-- Cumulables, contrairement aux formats.
with resto as (select id from public.restaurants where name ilike '%melyza%' order by created_at limit 1),
sups (plat, nom, prix) as (values
  ('Pizza Végétarienne', 'Viande hachée', 250),
  ('Pizza Végétarienne', 'Merguez', 250),
  ('Pizza Végétarienne', 'Poulet', 250),
  ('Pizza Végétarienne', 'Thon', 250),
  ('Pizza Végétarienne', 'Champignons', 250),
  ('Pizza Végétarienne', 'Cheddar', 250),
  ('Pizza Végétarienne', 'Mozzarella', 250),
  ('Pizza Végétarienne', 'Camembert', 250),
  ('Pizza Végétarienne', 'Gruyère', 250),
  ('Pizza Végétarienne', 'Pâte américaine graines de sésame', 100),
  ('Pizza Végétarienne', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Thon', 'Viande hachée', 250),
  ('Pizza Thon', 'Merguez', 250),
  ('Pizza Thon', 'Poulet', 250),
  ('Pizza Thon', 'Thon', 250),
  ('Pizza Thon', 'Champignons', 250),
  ('Pizza Thon', 'Cheddar', 250),
  ('Pizza Thon', 'Mozzarella', 250),
  ('Pizza Thon', 'Camembert', 250),
  ('Pizza Thon', 'Gruyère', 250),
  ('Pizza Thon', 'Pâte américaine graines de sésame', 100),
  ('Pizza Thon', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Chicken', 'Viande hachée', 250),
  ('Pizza Chicken', 'Merguez', 250),
  ('Pizza Chicken', 'Poulet', 250),
  ('Pizza Chicken', 'Thon', 250),
  ('Pizza Chicken', 'Champignons', 250),
  ('Pizza Chicken', 'Cheddar', 250),
  ('Pizza Chicken', 'Mozzarella', 250),
  ('Pizza Chicken', 'Camembert', 250),
  ('Pizza Chicken', 'Gruyère', 250),
  ('Pizza Chicken', 'Pâte américaine graines de sésame', 100),
  ('Pizza Chicken', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Américaine', 'Viande hachée', 250),
  ('Pizza Américaine', 'Merguez', 250),
  ('Pizza Américaine', 'Poulet', 250),
  ('Pizza Américaine', 'Thon', 250),
  ('Pizza Américaine', 'Champignons', 250),
  ('Pizza Américaine', 'Cheddar', 250),
  ('Pizza Américaine', 'Mozzarella', 250),
  ('Pizza Américaine', 'Camembert', 250),
  ('Pizza Américaine', 'Gruyère', 250),
  ('Pizza Américaine', 'Pâte américaine graines de sésame', 100),
  ('Pizza Américaine', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Tropicale', 'Viande hachée', 250),
  ('Pizza Tropicale', 'Merguez', 250),
  ('Pizza Tropicale', 'Poulet', 250),
  ('Pizza Tropicale', 'Thon', 250),
  ('Pizza Tropicale', 'Champignons', 250),
  ('Pizza Tropicale', 'Cheddar', 250),
  ('Pizza Tropicale', 'Mozzarella', 250),
  ('Pizza Tropicale', 'Camembert', 250),
  ('Pizza Tropicale', 'Gruyère', 250),
  ('Pizza Tropicale', 'Pâte américaine graines de sésame', 100),
  ('Pizza Tropicale', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Orientale', 'Viande hachée', 250),
  ('Pizza Orientale', 'Merguez', 250),
  ('Pizza Orientale', 'Poulet', 250),
  ('Pizza Orientale', 'Thon', 250),
  ('Pizza Orientale', 'Champignons', 250),
  ('Pizza Orientale', 'Cheddar', 250),
  ('Pizza Orientale', 'Mozzarella', 250),
  ('Pizza Orientale', 'Camembert', 250),
  ('Pizza Orientale', 'Gruyère', 250),
  ('Pizza Orientale', 'Pâte américaine graines de sésame', 100),
  ('Pizza Orientale', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Barbecue', 'Viande hachée', 250),
  ('Pizza Barbecue', 'Merguez', 250),
  ('Pizza Barbecue', 'Poulet', 250),
  ('Pizza Barbecue', 'Thon', 250),
  ('Pizza Barbecue', 'Champignons', 250),
  ('Pizza Barbecue', 'Cheddar', 250),
  ('Pizza Barbecue', 'Mozzarella', 250),
  ('Pizza Barbecue', 'Camembert', 250),
  ('Pizza Barbecue', 'Gruyère', 250),
  ('Pizza Barbecue', 'Pâte américaine graines de sésame', 100),
  ('Pizza Barbecue', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Spéciale', 'Viande hachée', 250),
  ('Pizza Spéciale', 'Merguez', 250),
  ('Pizza Spéciale', 'Poulet', 250),
  ('Pizza Spéciale', 'Thon', 250),
  ('Pizza Spéciale', 'Champignons', 250),
  ('Pizza Spéciale', 'Cheddar', 250),
  ('Pizza Spéciale', 'Mozzarella', 250),
  ('Pizza Spéciale', 'Camembert', 250),
  ('Pizza Spéciale', 'Gruyère', 250),
  ('Pizza Spéciale', 'Pâte américaine graines de sésame', 100),
  ('Pizza Spéciale', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Mix Spécial', 'Viande hachée', 250),
  ('Pizza Mix Spécial', 'Merguez', 250),
  ('Pizza Mix Spécial', 'Poulet', 250),
  ('Pizza Mix Spécial', 'Thon', 250),
  ('Pizza Mix Spécial', 'Champignons', 250),
  ('Pizza Mix Spécial', 'Cheddar', 250),
  ('Pizza Mix Spécial', 'Mozzarella', 250),
  ('Pizza Mix Spécial', 'Camembert', 250),
  ('Pizza Mix Spécial', 'Gruyère', 250),
  ('Pizza Mix Spécial', 'Pâte américaine graines de sésame', 100),
  ('Pizza Mix Spécial', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Fish House', 'Viande hachée', 250),
  ('Pizza Fish House', 'Merguez', 250),
  ('Pizza Fish House', 'Poulet', 250),
  ('Pizza Fish House', 'Thon', 250),
  ('Pizza Fish House', 'Champignons', 250),
  ('Pizza Fish House', 'Cheddar', 250),
  ('Pizza Fish House', 'Mozzarella', 250),
  ('Pizza Fish House', 'Camembert', 250),
  ('Pizza Fish House', 'Gruyère', 250),
  ('Pizza Fish House', 'Pâte américaine graines de sésame', 100),
  ('Pizza Fish House', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Classique', 'Viande hachée', 250),
  ('Pizza Classique', 'Merguez', 250),
  ('Pizza Classique', 'Poulet', 250),
  ('Pizza Classique', 'Thon', 250),
  ('Pizza Classique', 'Champignons', 250),
  ('Pizza Classique', 'Cheddar', 250),
  ('Pizza Classique', 'Mozzarella', 250),
  ('Pizza Classique', 'Camembert', 250),
  ('Pizza Classique', 'Gruyère', 250),
  ('Pizza Classique', 'Pâte américaine graines de sésame', 100),
  ('Pizza Classique', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Queen', 'Viande hachée', 250),
  ('Pizza Queen', 'Merguez', 250),
  ('Pizza Queen', 'Poulet', 250),
  ('Pizza Queen', 'Thon', 250),
  ('Pizza Queen', 'Champignons', 250),
  ('Pizza Queen', 'Cheddar', 250),
  ('Pizza Queen', 'Mozzarella', 250),
  ('Pizza Queen', 'Camembert', 250),
  ('Pizza Queen', 'Gruyère', 250),
  ('Pizza Queen', 'Pâte américaine graines de sésame', 100),
  ('Pizza Queen', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza 3 Fromages', 'Viande hachée', 250),
  ('Pizza 3 Fromages', 'Merguez', 250),
  ('Pizza 3 Fromages', 'Poulet', 250),
  ('Pizza 3 Fromages', 'Thon', 250),
  ('Pizza 3 Fromages', 'Champignons', 250),
  ('Pizza 3 Fromages', 'Cheddar', 250),
  ('Pizza 3 Fromages', 'Mozzarella', 250),
  ('Pizza 3 Fromages', 'Camembert', 250),
  ('Pizza 3 Fromages', 'Gruyère', 250),
  ('Pizza 3 Fromages', 'Pâte américaine graines de sésame', 100),
  ('Pizza 3 Fromages', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza 4 Fromages', 'Viande hachée', 250),
  ('Pizza 4 Fromages', 'Merguez', 250),
  ('Pizza 4 Fromages', 'Poulet', 250),
  ('Pizza 4 Fromages', 'Thon', 250),
  ('Pizza 4 Fromages', 'Champignons', 250),
  ('Pizza 4 Fromages', 'Cheddar', 250),
  ('Pizza 4 Fromages', 'Mozzarella', 250),
  ('Pizza 4 Fromages', 'Camembert', 250),
  ('Pizza 4 Fromages', 'Gruyère', 250),
  ('Pizza 4 Fromages', 'Pâte américaine graines de sésame', 100),
  ('Pizza 4 Fromages', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Parisienne', 'Viande hachée', 250),
  ('Pizza Parisienne', 'Merguez', 250),
  ('Pizza Parisienne', 'Poulet', 250),
  ('Pizza Parisienne', 'Thon', 250),
  ('Pizza Parisienne', 'Champignons', 250),
  ('Pizza Parisienne', 'Cheddar', 250),
  ('Pizza Parisienne', 'Mozzarella', 250),
  ('Pizza Parisienne', 'Camembert', 250),
  ('Pizza Parisienne', 'Gruyère', 250),
  ('Pizza Parisienne', 'Pâte américaine graines de sésame', 100),
  ('Pizza Parisienne', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Poulet Fumé', 'Viande hachée', 250),
  ('Pizza Poulet Fumé', 'Merguez', 250),
  ('Pizza Poulet Fumé', 'Poulet', 250),
  ('Pizza Poulet Fumé', 'Thon', 250),
  ('Pizza Poulet Fumé', 'Champignons', 250),
  ('Pizza Poulet Fumé', 'Cheddar', 250),
  ('Pizza Poulet Fumé', 'Mozzarella', 250),
  ('Pizza Poulet Fumé', 'Camembert', 250),
  ('Pizza Poulet Fumé', 'Gruyère', 250),
  ('Pizza Poulet Fumé', 'Pâte américaine graines de sésame', 100),
  ('Pizza Poulet Fumé', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Chicago', 'Viande hachée', 250),
  ('Pizza Chicago', 'Merguez', 250),
  ('Pizza Chicago', 'Poulet', 250),
  ('Pizza Chicago', 'Thon', 250),
  ('Pizza Chicago', 'Champignons', 250),
  ('Pizza Chicago', 'Cheddar', 250),
  ('Pizza Chicago', 'Mozzarella', 250),
  ('Pizza Chicago', 'Camembert', 250),
  ('Pizza Chicago', 'Gruyère', 250),
  ('Pizza Chicago', 'Pâte américaine graines de sésame', 100),
  ('Pizza Chicago', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Chèvre Miel', 'Viande hachée', 250),
  ('Pizza Chèvre Miel', 'Merguez', 250),
  ('Pizza Chèvre Miel', 'Poulet', 250),
  ('Pizza Chèvre Miel', 'Thon', 250),
  ('Pizza Chèvre Miel', 'Champignons', 250),
  ('Pizza Chèvre Miel', 'Cheddar', 250),
  ('Pizza Chèvre Miel', 'Mozzarella', 250),
  ('Pizza Chèvre Miel', 'Camembert', 250),
  ('Pizza Chèvre Miel', 'Gruyère', 250),
  ('Pizza Chèvre Miel', 'Pâte américaine graines de sésame', 100),
  ('Pizza Chèvre Miel', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Saumon', 'Viande hachée', 250),
  ('Pizza Saumon', 'Merguez', 250),
  ('Pizza Saumon', 'Poulet', 250),
  ('Pizza Saumon', 'Thon', 250),
  ('Pizza Saumon', 'Champignons', 250),
  ('Pizza Saumon', 'Cheddar', 250),
  ('Pizza Saumon', 'Mozzarella', 250),
  ('Pizza Saumon', 'Camembert', 250),
  ('Pizza Saumon', 'Gruyère', 250),
  ('Pizza Saumon', 'Pâte américaine graines de sésame', 100),
  ('Pizza Saumon', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Spicy', 'Viande hachée', 250),
  ('Pizza Spicy', 'Merguez', 250),
  ('Pizza Spicy', 'Poulet', 250),
  ('Pizza Spicy', 'Thon', 250),
  ('Pizza Spicy', 'Champignons', 250),
  ('Pizza Spicy', 'Cheddar', 250),
  ('Pizza Spicy', 'Mozzarella', 250),
  ('Pizza Spicy', 'Camembert', 250),
  ('Pizza Spicy', 'Gruyère', 250),
  ('Pizza Spicy', 'Pâte américaine graines de sésame', 100),
  ('Pizza Spicy', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Anchois', 'Viande hachée', 250),
  ('Pizza Anchois', 'Merguez', 250),
  ('Pizza Anchois', 'Poulet', 250),
  ('Pizza Anchois', 'Thon', 250),
  ('Pizza Anchois', 'Champignons', 250),
  ('Pizza Anchois', 'Cheddar', 250),
  ('Pizza Anchois', 'Mozzarella', 250),
  ('Pizza Anchois', 'Camembert', 250),
  ('Pizza Anchois', 'Gruyère', 250),
  ('Pizza Anchois', 'Pâte américaine graines de sésame', 100),
  ('Pizza Anchois', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Boursin', 'Viande hachée', 250),
  ('Pizza Boursin', 'Merguez', 250),
  ('Pizza Boursin', 'Poulet', 250),
  ('Pizza Boursin', 'Thon', 250),
  ('Pizza Boursin', 'Champignons', 250),
  ('Pizza Boursin', 'Cheddar', 250),
  ('Pizza Boursin', 'Mozzarella', 250),
  ('Pizza Boursin', 'Camembert', 250),
  ('Pizza Boursin', 'Gruyère', 250),
  ('Pizza Boursin', 'Pâte américaine graines de sésame', 100),
  ('Pizza Boursin', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Pepperonis', 'Viande hachée', 250),
  ('Pizza Pepperonis', 'Merguez', 250),
  ('Pizza Pepperonis', 'Poulet', 250),
  ('Pizza Pepperonis', 'Thon', 250),
  ('Pizza Pepperonis', 'Champignons', 250),
  ('Pizza Pepperonis', 'Cheddar', 250),
  ('Pizza Pepperonis', 'Mozzarella', 250),
  ('Pizza Pepperonis', 'Camembert', 250),
  ('Pizza Pepperonis', 'Gruyère', 250),
  ('Pizza Pepperonis', 'Pâte américaine graines de sésame', 100),
  ('Pizza Pepperonis', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Végé Suprême', 'Viande hachée', 250),
  ('Pizza Végé Suprême', 'Merguez', 250),
  ('Pizza Végé Suprême', 'Poulet', 250),
  ('Pizza Végé Suprême', 'Thon', 250),
  ('Pizza Végé Suprême', 'Champignons', 250),
  ('Pizza Végé Suprême', 'Cheddar', 250),
  ('Pizza Végé Suprême', 'Mozzarella', 250),
  ('Pizza Végé Suprême', 'Camembert', 250),
  ('Pizza Végé Suprême', 'Gruyère', 250),
  ('Pizza Végé Suprême', 'Pâte américaine graines de sésame', 100),
  ('Pizza Végé Suprême', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Raclette', 'Viande hachée', 250),
  ('Pizza Raclette', 'Merguez', 250),
  ('Pizza Raclette', 'Poulet', 250),
  ('Pizza Raclette', 'Thon', 250),
  ('Pizza Raclette', 'Champignons', 250),
  ('Pizza Raclette', 'Cheddar', 250),
  ('Pizza Raclette', 'Mozzarella', 250),
  ('Pizza Raclette', 'Camembert', 250),
  ('Pizza Raclette', 'Gruyère', 250),
  ('Pizza Raclette', 'Pâte américaine graines de sésame', 100),
  ('Pizza Raclette', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Spéciale Melyza', 'Viande hachée', 250),
  ('Pizza Spéciale Melyza', 'Merguez', 250),
  ('Pizza Spéciale Melyza', 'Poulet', 250),
  ('Pizza Spéciale Melyza', 'Thon', 250),
  ('Pizza Spéciale Melyza', 'Champignons', 250),
  ('Pizza Spéciale Melyza', 'Cheddar', 250),
  ('Pizza Spéciale Melyza', 'Mozzarella', 250),
  ('Pizza Spéciale Melyza', 'Camembert', 250),
  ('Pizza Spéciale Melyza', 'Gruyère', 250),
  ('Pizza Spéciale Melyza', 'Pâte américaine graines de sésame', 100),
  ('Pizza Spéciale Melyza', 'Pâte américaine fourrée au fromage fondu', 150),
  ('My Pizza', 'Viande hachée', 250),
  ('My Pizza', 'Merguez', 250),
  ('My Pizza', 'Poulet', 250),
  ('My Pizza', 'Thon', 250),
  ('My Pizza', 'Champignons', 250),
  ('My Pizza', 'Cheddar', 250),
  ('My Pizza', 'Mozzarella', 250),
  ('My Pizza', 'Camembert', 250),
  ('My Pizza', 'Gruyère', 250),
  ('My Pizza', 'Pâte américaine graines de sésame', 100),
  ('My Pizza', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Pizza Quatre Saisons', 'Viande hachée', 250),
  ('Pizza Quatre Saisons', 'Merguez', 250),
  ('Pizza Quatre Saisons', 'Poulet', 250),
  ('Pizza Quatre Saisons', 'Thon', 250),
  ('Pizza Quatre Saisons', 'Champignons', 250),
  ('Pizza Quatre Saisons', 'Cheddar', 250),
  ('Pizza Quatre Saisons', 'Mozzarella', 250),
  ('Pizza Quatre Saisons', 'Camembert', 250),
  ('Pizza Quatre Saisons', 'Gruyère', 250),
  ('Pizza Quatre Saisons', 'Pâte américaine graines de sésame', 100),
  ('Pizza Quatre Saisons', 'Pâte américaine fourrée au fromage fondu', 150),
  ('Cheesecake Fraise', 'Nutella', 250),
  ('Cheesecake Fraise', 'Banane', 250),
  ('Cheesecake Fraise', 'Fruits secs', 250),
  ('Cheesecake Fraise', 'Ferrero', 250),
  ('Cheesecake Fraise', 'M&M’s', 250),
  ('Cheesecake Fraise', 'Twix', 250),
  ('Cheesecake Fraise', 'Kit-Kat', 250),
  ('Cheesecake Fraise', 'Lion', 250),
  ('Cheesecake Fraise', 'Mars', 250),
  ('Cheesecake Fraise', 'Snickers', 250),
  ('Cheesecake Fraise', 'Bounty', 250),
  ('Cheesecake Fraise', 'Raffaello', 250),
  ('Cheesecake Fraise', 'Bueno', 250),
  ('Cheesecake Fraise', 'Pistache', 250),
  ('Cheesecake Fraise', 'Boule de glace', 100),
  ('Cheesecake Lotus', 'Nutella', 250),
  ('Cheesecake Lotus', 'Banane', 250),
  ('Cheesecake Lotus', 'Fruits secs', 250),
  ('Cheesecake Lotus', 'Ferrero', 250),
  ('Cheesecake Lotus', 'M&M’s', 250),
  ('Cheesecake Lotus', 'Twix', 250),
  ('Cheesecake Lotus', 'Kit-Kat', 250),
  ('Cheesecake Lotus', 'Lion', 250),
  ('Cheesecake Lotus', 'Mars', 250),
  ('Cheesecake Lotus', 'Snickers', 250),
  ('Cheesecake Lotus', 'Bounty', 250),
  ('Cheesecake Lotus', 'Raffaello', 250),
  ('Cheesecake Lotus', 'Bueno', 250),
  ('Cheesecake Lotus', 'Pistache', 250),
  ('Cheesecake Lotus', 'Boule de glace', 100),
  ('Cheesecake Oreo', 'Nutella', 250),
  ('Cheesecake Oreo', 'Banane', 250),
  ('Cheesecake Oreo', 'Fruits secs', 250),
  ('Cheesecake Oreo', 'Ferrero', 250),
  ('Cheesecake Oreo', 'M&M’s', 250),
  ('Cheesecake Oreo', 'Twix', 250),
  ('Cheesecake Oreo', 'Kit-Kat', 250),
  ('Cheesecake Oreo', 'Lion', 250),
  ('Cheesecake Oreo', 'Mars', 250),
  ('Cheesecake Oreo', 'Snickers', 250),
  ('Cheesecake Oreo', 'Bounty', 250),
  ('Cheesecake Oreo', 'Raffaello', 250),
  ('Cheesecake Oreo', 'Bueno', 250),
  ('Cheesecake Oreo', 'Pistache', 250),
  ('Cheesecake Oreo', 'Boule de glace', 100),
  ('Cheesecake Bueno', 'Nutella', 250),
  ('Cheesecake Bueno', 'Banane', 250),
  ('Cheesecake Bueno', 'Fruits secs', 250),
  ('Cheesecake Bueno', 'Ferrero', 250),
  ('Cheesecake Bueno', 'M&M’s', 250),
  ('Cheesecake Bueno', 'Twix', 250),
  ('Cheesecake Bueno', 'Kit-Kat', 250),
  ('Cheesecake Bueno', 'Lion', 250),
  ('Cheesecake Bueno', 'Mars', 250),
  ('Cheesecake Bueno', 'Snickers', 250),
  ('Cheesecake Bueno', 'Bounty', 250),
  ('Cheesecake Bueno', 'Raffaello', 250),
  ('Cheesecake Bueno', 'Bueno', 250),
  ('Cheesecake Bueno', 'Pistache', 250),
  ('Cheesecake Bueno', 'Boule de glace', 100),
  ('Cheesecake Citron', 'Nutella', 250),
  ('Cheesecake Citron', 'Banane', 250),
  ('Cheesecake Citron', 'Fruits secs', 250),
  ('Cheesecake Citron', 'Ferrero', 250),
  ('Cheesecake Citron', 'M&M’s', 250),
  ('Cheesecake Citron', 'Twix', 250),
  ('Cheesecake Citron', 'Kit-Kat', 250),
  ('Cheesecake Citron', 'Lion', 250),
  ('Cheesecake Citron', 'Mars', 250),
  ('Cheesecake Citron', 'Snickers', 250),
  ('Cheesecake Citron', 'Bounty', 250),
  ('Cheesecake Citron', 'Raffaello', 250),
  ('Cheesecake Citron', 'Bueno', 250),
  ('Cheesecake Citron', 'Pistache', 250),
  ('Cheesecake Citron', 'Boule de glace', 100),
  ('Cheesecake Nutella', 'Nutella', 250),
  ('Cheesecake Nutella', 'Banane', 250),
  ('Cheesecake Nutella', 'Fruits secs', 250),
  ('Cheesecake Nutella', 'Ferrero', 250),
  ('Cheesecake Nutella', 'M&M’s', 250),
  ('Cheesecake Nutella', 'Twix', 250),
  ('Cheesecake Nutella', 'Kit-Kat', 250),
  ('Cheesecake Nutella', 'Lion', 250),
  ('Cheesecake Nutella', 'Mars', 250),
  ('Cheesecake Nutella', 'Snickers', 250),
  ('Cheesecake Nutella', 'Bounty', 250),
  ('Cheesecake Nutella', 'Raffaello', 250),
  ('Cheesecake Nutella', 'Bueno', 250),
  ('Cheesecake Nutella', 'Pistache', 250),
  ('Cheesecake Nutella', 'Boule de glace', 100),
  ('Cheesecake Pistache', 'Nutella', 250),
  ('Cheesecake Pistache', 'Banane', 250),
  ('Cheesecake Pistache', 'Fruits secs', 250),
  ('Cheesecake Pistache', 'Ferrero', 250),
  ('Cheesecake Pistache', 'M&M’s', 250),
  ('Cheesecake Pistache', 'Twix', 250),
  ('Cheesecake Pistache', 'Kit-Kat', 250),
  ('Cheesecake Pistache', 'Lion', 250),
  ('Cheesecake Pistache', 'Mars', 250),
  ('Cheesecake Pistache', 'Snickers', 250),
  ('Cheesecake Pistache', 'Bounty', 250),
  ('Cheesecake Pistache', 'Raffaello', 250),
  ('Cheesecake Pistache', 'Bueno', 250),
  ('Cheesecake Pistache', 'Pistache', 250),
  ('Cheesecake Pistache', 'Boule de glace', 100),
  ('Crêpe Nutella', 'Nutella', 250),
  ('Crêpe Nutella', 'Banane', 250),
  ('Crêpe Nutella', 'Fruits secs', 250),
  ('Crêpe Nutella', 'Ferrero', 250),
  ('Crêpe Nutella', 'M&M’s', 250),
  ('Crêpe Nutella', 'Twix', 250),
  ('Crêpe Nutella', 'Kit-Kat', 250),
  ('Crêpe Nutella', 'Lion', 250),
  ('Crêpe Nutella', 'Mars', 250),
  ('Crêpe Nutella', 'Snickers', 250),
  ('Crêpe Nutella', 'Bounty', 250),
  ('Crêpe Nutella', 'Raffaello', 250),
  ('Crêpe Nutella', 'Bueno', 250),
  ('Crêpe Nutella', 'Pistache', 250),
  ('Crêpe Nutella', 'Boule de glace', 100),
  ('Crêpe Banane', 'Nutella', 250),
  ('Crêpe Banane', 'Banane', 250),
  ('Crêpe Banane', 'Fruits secs', 250),
  ('Crêpe Banane', 'Ferrero', 250),
  ('Crêpe Banane', 'M&M’s', 250),
  ('Crêpe Banane', 'Twix', 250),
  ('Crêpe Banane', 'Kit-Kat', 250),
  ('Crêpe Banane', 'Lion', 250),
  ('Crêpe Banane', 'Mars', 250),
  ('Crêpe Banane', 'Snickers', 250),
  ('Crêpe Banane', 'Bounty', 250),
  ('Crêpe Banane', 'Raffaello', 250),
  ('Crêpe Banane', 'Bueno', 250),
  ('Crêpe Banane', 'Pistache', 250),
  ('Crêpe Banane', 'Boule de glace', 100),
  ('Crêpe Pistache', 'Nutella', 250),
  ('Crêpe Pistache', 'Banane', 250),
  ('Crêpe Pistache', 'Fruits secs', 250),
  ('Crêpe Pistache', 'Ferrero', 250),
  ('Crêpe Pistache', 'M&M’s', 250),
  ('Crêpe Pistache', 'Twix', 250),
  ('Crêpe Pistache', 'Kit-Kat', 250),
  ('Crêpe Pistache', 'Lion', 250),
  ('Crêpe Pistache', 'Mars', 250),
  ('Crêpe Pistache', 'Snickers', 250),
  ('Crêpe Pistache', 'Bounty', 250),
  ('Crêpe Pistache', 'Raffaello', 250),
  ('Crêpe Pistache', 'Bueno', 250),
  ('Crêpe Pistache', 'Pistache', 250),
  ('Crêpe Pistache', 'Boule de glace', 100),
  ('Crêpe Lotus', 'Nutella', 250),
  ('Crêpe Lotus', 'Banane', 250),
  ('Crêpe Lotus', 'Fruits secs', 250),
  ('Crêpe Lotus', 'Ferrero', 250),
  ('Crêpe Lotus', 'M&M’s', 250),
  ('Crêpe Lotus', 'Twix', 250),
  ('Crêpe Lotus', 'Kit-Kat', 250),
  ('Crêpe Lotus', 'Lion', 250),
  ('Crêpe Lotus', 'Mars', 250),
  ('Crêpe Lotus', 'Snickers', 250),
  ('Crêpe Lotus', 'Bounty', 250),
  ('Crêpe Lotus', 'Raffaello', 250),
  ('Crêpe Lotus', 'Bueno', 250),
  ('Crêpe Lotus', 'Pistache', 250),
  ('Crêpe Lotus', 'Boule de glace', 100),
  ('Crêpe Fraise', 'Nutella', 250),
  ('Crêpe Fraise', 'Banane', 250),
  ('Crêpe Fraise', 'Fruits secs', 250),
  ('Crêpe Fraise', 'Ferrero', 250),
  ('Crêpe Fraise', 'M&M’s', 250),
  ('Crêpe Fraise', 'Twix', 250),
  ('Crêpe Fraise', 'Kit-Kat', 250),
  ('Crêpe Fraise', 'Lion', 250),
  ('Crêpe Fraise', 'Mars', 250),
  ('Crêpe Fraise', 'Snickers', 250),
  ('Crêpe Fraise', 'Bounty', 250),
  ('Crêpe Fraise', 'Raffaello', 250),
  ('Crêpe Fraise', 'Bueno', 250),
  ('Crêpe Fraise', 'Pistache', 250),
  ('Crêpe Fraise', 'Boule de glace', 100),
  ('Crêpe Oreo', 'Nutella', 250),
  ('Crêpe Oreo', 'Banane', 250),
  ('Crêpe Oreo', 'Fruits secs', 250),
  ('Crêpe Oreo', 'Ferrero', 250),
  ('Crêpe Oreo', 'M&M’s', 250),
  ('Crêpe Oreo', 'Twix', 250),
  ('Crêpe Oreo', 'Kit-Kat', 250),
  ('Crêpe Oreo', 'Lion', 250),
  ('Crêpe Oreo', 'Mars', 250),
  ('Crêpe Oreo', 'Snickers', 250),
  ('Crêpe Oreo', 'Bounty', 250),
  ('Crêpe Oreo', 'Raffaello', 250),
  ('Crêpe Oreo', 'Bueno', 250),
  ('Crêpe Oreo', 'Pistache', 250),
  ('Crêpe Oreo', 'Boule de glace', 100),
  ('Crêpe Fruits Secs', 'Nutella', 250),
  ('Crêpe Fruits Secs', 'Banane', 250),
  ('Crêpe Fruits Secs', 'Fruits secs', 250),
  ('Crêpe Fruits Secs', 'Ferrero', 250),
  ('Crêpe Fruits Secs', 'M&M’s', 250),
  ('Crêpe Fruits Secs', 'Twix', 250),
  ('Crêpe Fruits Secs', 'Kit-Kat', 250),
  ('Crêpe Fruits Secs', 'Lion', 250),
  ('Crêpe Fruits Secs', 'Mars', 250),
  ('Crêpe Fruits Secs', 'Snickers', 250),
  ('Crêpe Fruits Secs', 'Bounty', 250),
  ('Crêpe Fruits Secs', 'Raffaello', 250),
  ('Crêpe Fruits Secs', 'Bueno', 250),
  ('Crêpe Fruits Secs', 'Pistache', 250),
  ('Crêpe Fruits Secs', 'Boule de glace', 100),
  ('Crêpe Fruits', 'Nutella', 250),
  ('Crêpe Fruits', 'Banane', 250),
  ('Crêpe Fruits', 'Fruits secs', 250),
  ('Crêpe Fruits', 'Ferrero', 250),
  ('Crêpe Fruits', 'M&M’s', 250),
  ('Crêpe Fruits', 'Twix', 250),
  ('Crêpe Fruits', 'Kit-Kat', 250),
  ('Crêpe Fruits', 'Lion', 250),
  ('Crêpe Fruits', 'Mars', 250),
  ('Crêpe Fruits', 'Snickers', 250),
  ('Crêpe Fruits', 'Bounty', 250),
  ('Crêpe Fruits', 'Raffaello', 250),
  ('Crêpe Fruits', 'Bueno', 250),
  ('Crêpe Fruits', 'Pistache', 250),
  ('Crêpe Fruits', 'Boule de glace', 100),
  ('Crêpe Bounty', 'Nutella', 250),
  ('Crêpe Bounty', 'Banane', 250),
  ('Crêpe Bounty', 'Fruits secs', 250),
  ('Crêpe Bounty', 'Ferrero', 250),
  ('Crêpe Bounty', 'M&M’s', 250),
  ('Crêpe Bounty', 'Twix', 250),
  ('Crêpe Bounty', 'Kit-Kat', 250),
  ('Crêpe Bounty', 'Lion', 250),
  ('Crêpe Bounty', 'Mars', 250),
  ('Crêpe Bounty', 'Snickers', 250),
  ('Crêpe Bounty', 'Bounty', 250),
  ('Crêpe Bounty', 'Raffaello', 250),
  ('Crêpe Bounty', 'Bueno', 250),
  ('Crêpe Bounty', 'Pistache', 250),
  ('Crêpe Bounty', 'Boule de glace', 100),
  ('Crêpe Bueno', 'Nutella', 250),
  ('Crêpe Bueno', 'Banane', 250),
  ('Crêpe Bueno', 'Fruits secs', 250),
  ('Crêpe Bueno', 'Ferrero', 250),
  ('Crêpe Bueno', 'M&M’s', 250),
  ('Crêpe Bueno', 'Twix', 250),
  ('Crêpe Bueno', 'Kit-Kat', 250),
  ('Crêpe Bueno', 'Lion', 250),
  ('Crêpe Bueno', 'Mars', 250),
  ('Crêpe Bueno', 'Snickers', 250),
  ('Crêpe Bueno', 'Bounty', 250),
  ('Crêpe Bueno', 'Raffaello', 250),
  ('Crêpe Bueno', 'Bueno', 250),
  ('Crêpe Bueno', 'Pistache', 250),
  ('Crêpe Bueno', 'Boule de glace', 100),
  ('Crêpe El Mordjene', 'Nutella', 250),
  ('Crêpe El Mordjene', 'Banane', 250),
  ('Crêpe El Mordjene', 'Fruits secs', 250),
  ('Crêpe El Mordjene', 'Ferrero', 250),
  ('Crêpe El Mordjene', 'M&M’s', 250),
  ('Crêpe El Mordjene', 'Twix', 250),
  ('Crêpe El Mordjene', 'Kit-Kat', 250),
  ('Crêpe El Mordjene', 'Lion', 250),
  ('Crêpe El Mordjene', 'Mars', 250),
  ('Crêpe El Mordjene', 'Snickers', 250),
  ('Crêpe El Mordjene', 'Bounty', 250),
  ('Crêpe El Mordjene', 'Raffaello', 250),
  ('Crêpe El Mordjene', 'Bueno', 250),
  ('Crêpe El Mordjene', 'Pistache', 250),
  ('Crêpe El Mordjene', 'Boule de glace', 100),
  ('Crêpe Spéciale', 'Nutella', 250),
  ('Crêpe Spéciale', 'Banane', 250),
  ('Crêpe Spéciale', 'Fruits secs', 250),
  ('Crêpe Spéciale', 'Ferrero', 250),
  ('Crêpe Spéciale', 'M&M’s', 250),
  ('Crêpe Spéciale', 'Twix', 250),
  ('Crêpe Spéciale', 'Kit-Kat', 250),
  ('Crêpe Spéciale', 'Lion', 250),
  ('Crêpe Spéciale', 'Mars', 250),
  ('Crêpe Spéciale', 'Snickers', 250),
  ('Crêpe Spéciale', 'Bounty', 250),
  ('Crêpe Spéciale', 'Raffaello', 250),
  ('Crêpe Spéciale', 'Bueno', 250),
  ('Crêpe Spéciale', 'Pistache', 250),
  ('Crêpe Spéciale', 'Boule de glace', 100),
  ('Mousse au Chocolat', 'Boule de glace', 100),
  ('Crème Brûlée', 'Boule de glace', 100),
  ('Fondant au Chocolat', 'Boule de glace', 100),
  ('Maxi Fruits', 'Boule de glace', 100),
  ('Tiramisu', 'Boule de glace', 100),
  ('Tiramisu Pistache', 'Boule de glace', 100),
  ('Tiramisu Chocolat', 'Boule de glace', 100),
  ('Tiramisu Citron', 'Boule de glace', 100),
  ('Cappuccino', 'Vanille', 0),
  ('Cappuccino', 'Caramel', 0),
  ('Cappuccino', 'Noisette', 0),
  ('Mocha', 'Vanille', 0),
  ('Mocha', 'Caramel', 0),
  ('Mocha', 'Noisette', 0),
  ('Flat White', 'Vanille', 0),
  ('Flat White', 'Caramel', 0),
  ('Flat White', 'Noisette', 0),
  ('Latte', 'Vanille', 0),
  ('Latte', 'Caramel', 0),
  ('Latte', 'Noisette', 0)
)
insert into public.menu_options (menu_item_id, name, extra_price, is_active)
select m.id, s.nom, s.prix, true
  from sups s
  cross join resto r
  join public.menu_items m on m.restaurant_id = r.id and m.name = s.plat
 where not exists (
   select 1 from public.menu_options o where o.menu_item_id = m.id and o.name = s.nom
 );


-- ---------------------------------------------------------- VÉRIFICATION
select r.name as restaurant,
       count(distinct m.id) as plats,
       count(distinct v.id) as formats,
       count(distinct o.id) as supplements
  from public.restaurants r
  left join public.menu_items m on m.restaurant_id = r.id
  left join public.menu_variants v on v.menu_item_id = m.id
  left join public.menu_options o on o.menu_item_id = m.id
 where r.name ilike '%melyza%'
 group by r.name;
